public class cotu {
    public static void main(String[] args) {
        System.out.println("siema");
        System.out.println("siema");
        System.out.println("siema");
        System.out.println("siema");
        System.out.println("siema");
        System.out.println("siema");
        System.out.println("siema");
        System.out.println("siema");
        System.out.println("siema");
        System.out.println("siema");
        System.out.println("siema");
        System.out.println("siema");
        System.out.println("siema");
        System.out.println("siema");
        System.out.println("siema");
        System.out.println("siema");
        System.out.println("siema");
        System.out.println("siema");
        System.out.println("siema");
        System.out.println("siema");
        System.out.println("siema");
        System.out.println("siema");
        System.out.println("siema");
        System.out.println("siema");
        System.out.println("siema");
    }
}
